configMapGenerator:
- files:
  - application.yml
  name: 82241017-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
images:
- name: ceappacr.azurecr.io/82241017
  newTag: "202411121138"
- name: cepgstapacr.azurecr.io/82241017
  newTag: "202411120000"
